### ISSUE TITLE
SVG code for burger for responsive main menu not working in Django

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/fundament#20]
The code used in [fundament.min.css](https://github.com/acdh-oeaw/fundament/blob/master/dist/fundament/css/fundament.min.css) to generate the SVG for the burger icon for small screens

```css
.navbar-toggler-icon{background-image:url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(0, 0, 0, 0.7)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E")}
```

does not work in APIS(-RDF) apps because it conflicts with Django's CSP settings.

As a consequence, the icon is not displayed at all, which makes it impossible to navigate these apps on mobile devices. (!)

**Error the code generates**
Firefox
> Content Security Policy: The page's settings blocked the loading of a resource at data:image/svg+xml;charset=utf8,%3Csvg v… ("default-src").

Chrome
> Refused to load the image 'data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(0, 0, 0, 0.7)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-inline' cdnjs.cloudflare.com cdn.jsdelivr.net fonts.googleapis.com ajax.googleapis.com cdn.rawgit.com *.acdh.oeaw.ac.at unpkg.com fonts.gstatic.com cdn.datatables.net code.highcharts.com *.acdh-dev.oeaw.ac.at *.acdh.oeaw.ac.at openstreetmap.org *.openstreetmap.org". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

**Live examples**
https://apis-jelinek.acdh-dev.oeaw.ac.at/apis/
https://sicprod.acdh-dev.oeaw.ac.at/

**Proposed solution**
I was able to work around the problem by creating an actual SVG file for the burger icon and by overriding fundament's CSS in our Django templates. As a longer-term solution, fundament's `navbar-toggler-icon`'s `background-image` should do the same instead of creating the SVG on the fly.
